# Catppuccin-inspired, compact single-line prompt.
 typeset -g POWERLEVEL9K_MODE=nerdfont-complete
 typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs prompt_char)
 typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs)
 typeset -g POWERLEVEL9K_ICON_PADDING=none
 typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
 typeset -g POWERLEVEL9K_BACKGROUND=
 typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
 typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
 typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
 typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
 typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
 typeset -g POWERLEVEL9K_DIR_FOREGROUND=111
 typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
 typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=117
 typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
 typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
 typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
 typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=151
 typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=222
 typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=222
 typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=245
 typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=151
 typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=211
 typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
 typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
 typeset -g POWERLEVEL9K_STATUS_OK=false
 typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=211
 typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
 typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=222
 typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
 typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=183
 typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
 typeset -g POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

(( $+functions[p10k] )) && p10k reload
